server:
    verbosity: 3
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-ip6: yes
    do-udp: yes
    do-tcp: yes
    access-control: 0.0.0.0/0 allow
    root-hints: "/etc/unbound/root.hints"
    prefetch: yes
# enable DNSSEC
    auto-trust-anchor-file: "/usr/share/dnssec-root/trusted-key.key"
# disable user privilege protection
    username: ""
# option to harden against unverified glue
    harden-unverified-glue: yes
#
    aggressive-nsec: yes
    hide-identity: yes
    hide-version: yes
    use-caps-for-id: yes
    private-address: 192.168.0.0/16
    private-address: 192.168.5.0/24
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
